### ISSUE TITLE
AppCompat does not support Theme.Swipe.Back features

### ISSUE THREAD

**Issue by jabzaVR** [liuguangqiang/SwipeBack#21]
When creating an activity using the SwipeBack theme, the aplication crashes with the following error:

`java.lang.IllegalArgumentException: AppCompat does not support the current theme features: { windowActionBar: false, windowActionBarOverlay: false, android:windowIsFloating: false, windowActionModeOverlay: false, windowNoTitle: false`

Presumably, as a result, swiping back does not show the activity behind it but instead fades it in after the animation completes.

**Comment by krishnameena** [comment]
Update your style to this

 <style name="ThemeSwipeBack" parent="Theme.Swipe.Back">
        <item name="windowActionBar">false</item>
        <item name="windowNoTitle">true</item>
        <item name="colorPrimary">@color/primary</item>
        <item name="colorPrimaryDark">@color/primary_dark</item>
        <item name="android:windowIsTranslucent">true</item>
        <item name="android:windowBackground">@android:color/transparent</item>
    </style>
