### ISSUE TITLE
Background screen blank when swipe

### ISSUE THREAD

**Issue by riten7** [liuguangqiang/SwipeBack#25]
When i was swiping left the activity, the background was blank until complete close of swipe activity.But i want to show background activity on swipe.Any help ??

**Comment by tux-world** [comment]
@riten7 i have this same problem. could you resolve that?

**Comment by shilch** [comment]
Hi, I had the same problem. You have to add these two lines to your styles.xml:
```
<item name="android:windowIsTranslucent">true</item>
<item name="android:windowBackground">@android:color/transparent</item>
```
