### ISSUE TITLE
Sensitivity, DragEdge.VERTICAL and DragEdge.HORIZONTAL

### ISSUE THREAD

**Issue by KaNcHeR** [liuguangqiang/SwipeBack#26]
It will be cool if it will be possible to adjust the sensitivity. A swipe is also simultaneously in different directions, for example DragEdge.VERTICAL and DragEdge.HORIZONTAL.

**Comment by Mahdiazadbar** [comment]
+1

**Comment by evrenozturkhurriyet** [comment]
In SwipeBackLayout there is a dragHelper.
You might adjust the sensitivity while creating the the helper.
1 is full sensitivity. I find it usefull to use as 0.1f.

        viewDragHelper = ViewDragHelper.create(this, 0.1f, new ViewDragHelperCallBack());

**Comment by pavel163** [comment]
@KaNcHeR Hello. While you can use this solution https://github.com/pavel163/SwipeBack

**Comment by KaNcHeR** [comment]
@pavel163 Спасибо!
