### ISSUE TITLE
can not scroll  with webview  

### ISSUE THREAD

**Issue by adamin1990** [liuguangqiang/SwipeBack#8]
my activity extends  Activity  and  in the layout xml  hava a webview ,but it can not scroll.

**Comment by liuguangqiang** [comment]
I’m so sorry. I didn’t read your message. Could you try again? Set your activity extends SwipeBackActivity.

**Comment by liuguangqiang** [comment]
I have found out the problem and fixed it.Thanks.

**Comment by adamin1990** [comment]
@liuguangqiang  thanks
